baseURL: https://coalton-lang.github.io/
languageCode: en-us
title: The Coalton Programming Language
theme: PaperMod
#googleAnalytics: UA-123456789-1

taxonomies:
  tag: tags

permalinks:
  post: /:contentbasename/

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: blog
      name: Blog
      url: /post/
      weight: 2
    - identifier: github
      name: GitHub
      url: https://github.com/coalton-lang/coalton
      weight: 3
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - identifier: reference
      name: Reference
      url: /reference/
      weight: 5

params:
  env: production
  title: The Coalton Programming Language
  description: "A statically typed, functional programming language that compiles to Common Lisp"
  keywords: [coalton, functional programming, lisp, static types]
  DateFormat: "January 2, 2006"
  defaultTheme: light
  disableThemeToggle: true

  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  disableAnchoredHeadings: true

  assets:
    disableHLJS: true

  label:
    text: " "
    icon: /site-images/coalton-logotype-gray.svg
    iconHeight: 24

  profileMode:
    enabled: false

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  footerText: "Copyright © 2018–2025 Coalton Developers. [source](https://github.com/coalton-lang/coalton-website) · [rss](/index.xml)"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: bw
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
